### ISSUE TITLE
fio: attempt to access beyond end of device observed during blktests block/027

### ISSUE THREAD

**Issue by yizhanglinux** [osandov/blktests#148]
Hi
I found this info during blktests block/027, not sure if it was expected, could you help check it, thanks.

```
[ 7049.231614] fio: attempt to access beyond end of device
               sdd: rw=0, sector=39296704, nr_sectors = 8 limit=0
[ 7049.268392] sd 15:0:0:2: [sdd] Synchronizing SCSI cache
[ 7049.321408] sd 15:0:0:20: [sdv] Synchronizing SCSI cache
[ 7049.363430] sd 15:0:0:3: [sde] Synchronizing SCSI cache
[ 7049.369660] fio: attempt to access beyond end of device
               sdf: rw=0, sector=19979560, nr_sectors = 8 limit=0
```

**Comment by kawasaki** [comment]
Hi @yizhanglinux , thanks for the report. Yeah, that message sounds suspicious. I took a look in the test case and kernel code, and concluded that the "fio: attempt to access beyond end of device" messages are expected. It prints that "limit=0", which means that the device has 0 capacity. This is expected since the test case does "echo 1 > /sys/block/sdX/device/delete" in parallel with the fio process. The echo ends up with this call chain: sd_remove() ->  del_gendisk() -> __blk_mark_disk_dead() -> set_capacity(disk, 0).  Now I'm confident that the message is expected and fine :)

**Comment by yizhanglinux** [comment]
Yeah, I was not aware of the delete operation for the scsi_debug, thanks for the update.
